name: Publish release

on:
  push:
    branches:
      - main

jobs:
  publish_release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Cargar todo el historial de git del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Instalar Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24.13.0"
      - name: Instalar dependencias del flujo
        run: npm install --no-save semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/git @semantic-release/github conventional-changelog-conventionalcommits
      - name: Instalar dependencia toml para Python
        run: pip install toml
      - name: Ejecutar semantic-release en modo dry-run para captar la pr贸xima versi贸n
        run: |
          npx semantic-release --dry-run > sr.log
          VERSION=$(grep -oP 'next release version is \K[0-9]+\.[0-9]+\.[0-9]+' sr.log || echo "")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Actualizar pyproject.toml con la nueva versi贸n
        run: python update_version.py ${{ env.VERSION }}
      - name: Verificar configuraci贸n de semantic-release
        run: npx semantic-release --dry-run
      - name: Ejecutar semantic-release
        run: npx semantic-release